services:
  app:
    build:
      context: .
      dockerfile: php.Dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html/example
  web:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www/html/example
      - ./default.conf:/etc/nginx/conf.d/default.conf
  db:
    image: mysql:8.0.34
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Tokyo
    volumes:
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
  mail:
    image: axllent/mailpit:v1.8
    container_name: mailpit
    ports:
      - 8025:8025
      - 1025:1025